version: "3.8"
services:
  php-cli:
    build:
      context: ./php/docker
      dockerfile: php-cli.dockerfile
    container_name: php-cli
    volumes:
      - ./php/bitrix-application:/var/www/project
  nginx:
    image: nginx:1.20.1-alpine
    ports:
      - "8093:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/bitrix-application:/var/www/project
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php/docker
      dockerfile: php-fpm.dockerfile
    container_name: php-fpm
    expose:
      - '9000'
    volumes:
      - ./php/bitrix-application:/var/www/project
